### ISSUE TITLE
PLAY ERROR

### ISSUE THREAD

**Issue by golivesid** [junioralive/box-stream#1]
can i add my own server to it

**Comment by junioralive** [comment]
Hey, The Error is due to the limit i have reached my limit for the free tier.

**Comment by golivesid** [comment]
Hi sir
How can i add my workers.dev server to it

**Comment by junioralive** [comment]
what is your telegram or maybe discord ?
we will talk there also provide me your workers.dev server link let me check

**Comment by golivesid** [comment]
@seeuadmin_bot

https://seeutera.golive8897.workers.dev/

**Comment by junioralive** [comment]
api is now up use my website

**Comment by golivesid** [comment]
Your website

How to add this to database
https://seeutera.golive8897.workers.dev/

**Comment by golivesid** [comment]
You're telegram id

**Comment by junioralive** [comment]
Please provide full parameter for example  https://seeutera.golive8897.workers.dev/?url={terrabox url}, i don't understand your backend

**Comment by golivesid** [comment]
Cam you tell me how to create the backend

**Comment by junioralive** [comment]
Oops you don't have a backend sorry man but my backend is not public yet, i will release a backend soon.

**Comment by golivesid** [comment]
can you teach how to create a backend in workers dev
