### ISSUE TITLE
the api responds with internal 500 error, alerting "error fetching video"

### ISSUE THREAD

**Issue by harsh7800** [junioralive/box-stream#3]

**Comment by junioralive** [comment]
the cookie, jstoken, dp-logid, has expired will fixed it soon thank you

**Comment by harsh7800** [comment]
> the cookie, jstoken, dp-logid, has expired will fix it soon thank you

works on the mobile but not on the desktop also add a loading status while fetching

**Comment by junioralive** [comment]
considered, thank you

**Comment by junioralive** [comment]
i have a made a new version this so i thought of archiving this
